version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    env_file:
      - .flaskenv

    volumes:
      - ./.flaskenv:/python-docker/.flaskenv

    command: >
      sh -c "sleep 5 && alembic -c migrations/alembic.ini -x db=dev upgrade head &&
             python3 -m flask run --host=0.0.0.0"

    ports:
      - 5000:5000

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    # ports:
    #   - 80:80  # Needed for the ACME HTTP-01 challenge.
    #   - 443:443

    network_mode: "host"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:2024-06-25-1
    env_file:
      - .flaskenv
    ports:
      - 3000:3000
    volumes:
    - ${PWD}/.pgadmin_servers.json:/pgadmin4/servers.json

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
